"$schema" = 'https://starship.rs/config-schema.json'

format = """$username$hostname $directory $git_branch $git_status $python$nodejs$rust 
$cmd_duration$character
"""

add_newline = false

command_timeout = 5000

palette = 'onedark'

[palettes.onedark]
black = '#000000'
pink = '#E06C75'
green = '#98C379'
orange = '#D19A66'
blue = '#61AFEF'
purple = '#C678DD'
cyan = '#56B6C2'
light_grey = '#ABB2BF'
dark_gray = '#5C6370'
white = '#FFFFFF'

[character]
format = '$symbol'
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'

[username]
style_user = 'bold cyan'
style_root = 'bold cyan'
format = '[$user]($style)'
show_always = true

[hostname]
style = 'bold cyan'
format = '[ $ssh_symbol$hostname]($style)'
ssh_only = true
ssh_symbol = '󱘖 '

[directory]
style = 'bold blue'
format = 'at [$path]($style)'
truncation_symbol = "󰉕 /"
truncate_to_repo = true
home_symbol = "󱂶 "

[git_branch]
style = 'bold pink'
format = 'on [$symbol$branch]($style)'
symbol = '󰊤 '

[git_status]
style = 'bold pink'
format = '[(\[$untracked$staged$modified$renamed$deleted\])]($style)'
ignore_submodules = true
untracked = '( $count )'
modified = '( $count )'
staged = '( $count )'
renamed = '( $count )'
deleted = '( $count )'

[python]
style = 'bold purple'
format = 'via [$symbol$version( $virtualenv)]($style)'
python_binary = 'python'
version_format = '$raw'
symbol = '󰌠 '

[nodejs]
style = 'bold purple'
format = 'via [$symbol($version)]($style)'
version_format = '$raw'
symbol = '󰎙 '

[rust]
style = 'bold purple'
format = 'via [$symbol($version)]($style)'
version_format = '$raw'
symbol = '󱘗 '


[cmd_duration]
style = 'bold orange'
format = 'took [$duration]($style)'
min_time = 5000
