"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](#004fa7)\
$username\
$hostname\
[](fg:#004fa7 bg:#0876b8)\
$directory\
[](fg:#0876b8 bg:#0097e1)\
$git_branch\
$git_status\
[](fg:#0097e1 bg:#00b8ff)\
$nodejs\
$python\
[](#00b8ff)
󰘧 \
"""

command_timeout = 5000

[hostname]
ssh_only = true
style = "bg:#004fa7 fg:white"
format = '[ $hostname ]($style)'

[username]
show_always = true
style_user = "bg:#004fa7 fg:white"
format = '[ $user ]($style)'

[directory]
style = "bg:#0876b8 fg:white"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = true
home_symbol = "󱂵 "

[git_branch]
symbol = "󰘬"
style = "bg:#0097e1 fg:white"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#0097e1 fg:white"
format = '[ $all_status $ahead_behind ]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:#00b8ff fg:white"
format = '[ $symbol $version ]($style)'

[python]
symbol = "󰌠"
style = "bg:#00b8ff fg:white"
format = '[ $symbol ${version} ]($style)'
