import = [
    "~/.config/alacritty/catppuccin-frappe.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 0.9
padding = { x = 0, y = 0}

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 16

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = true
