[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 0.9
padding = { x = 2, y = 0}

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 14

[colors.primary]
foreground = "#abb2bf"
background = "#282c34"

[colors.cursor]
text = "CellBackground"
cursor = "#528bff"

[colors.selection]
text = "CellBackground"
background = "#3e4451"

[colors.normal]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#828997"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = true
