"$schema" = 'https://starship.rs/config-schema.json'

format = """$username$hostname$directory$git_branch$python$nodejs$rust 
$cmd_duration$character
"""

add_newline = false

command_timeout = 5000

palette = 'onedark'

[palettes.onedark]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#828997"

[character]
format = '$symbol'
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'
vicmd_symbol = "[󰏤 ](bold green)"

[username]
style_user = 'bold cyan'
style_root = 'bold cyan'
format = '[$user]($style)'
show_always = true

[hostname]
style = 'bold cyan'
format = '[ $ssh_symbol$hostname]($style)'
ssh_only = true
ssh_symbol = '󱘖 '

[directory]
style = 'bold blue'
format = ' at [$path]($style)'
truncation_length = 5
truncation_symbol = "󰉕 /"
truncate_to_repo = true
home_symbol = "󱂶 "

[git_branch]
style = 'bold magenta'
format = ' on [$symbol$branch]($style)'
symbol = '󰊤 '

[python]
style = 'bold green'
format = ' via [$symbol$version( $virtualenv)]($style)'
python_binary = 'python'
version_format = '$raw'
symbol = '󰌠 '

[nodejs]
style = 'bold green'
format = ' via [$symbol($version)]($style)'
version_format = '$raw'
symbol = '󰎙 '

[rust]
style = 'bold green'
format = ' via [$symbol($version)]($style)'
version_format = '$raw'
symbol = '󱘗 '

[cmd_duration]
style = 'bold yellow'
format = 'took [$duration]($style)'
min_time = 5000
